### ISSUE TITLE
How to use Opencv with java for linux ?

### ISSUE THREAD

**Issue by ghost** [sgjava/install-opencv#1]
I added the opencv's native library for windows.

but, how can I add the opencv's native library for both linux 32 bit and 64 bit?

How to use Opencv with java for linux ?

**Comment by sgjava** [comment]
You would do that at runtime. In other words you can develop under Windows and deploy to Linux ARM for instance:

`java -Djava.library.path=/home/<username>/opencv/build/lib -cp /home/<username>/opencv/build/bin/opencv-430.jar:bin com.codeferm.opencv.Canny`

This is not something you do in Eclipse.
