### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by KroshkaRu** [sgjava/install-opencv#6]
Hello

I would suggest in append opencv_contrib in to the build
It is not installed in the opencv 3.x.x by defult anymore

Your script is excelent

**Comment by sgjava** [comment]
I was planning on doing that now that my build scripts are stable again. I will make that optional as well, so it can be built independently.

**Comment by KroshkaRu** [comment]
sounds good

I have just build opencv_contrib with update of your opencv installation script 
cmake  -D OPENCV_EXTRA_MODULES_PATH=/home/odroid/opencv_contrib/modules .......

**Comment by sgjava** [comment]
OK, I added installcontrib to config-opencv.sh and defaulted it to True. I'm testing the changes on a VM now, but it worked when I hard coded the cmake build option. Thanks for the suggestion.
