### ISSUE TITLE
class VideoWriter not found in Java

### ISSUE THREAD

**Issue by dvidalm** [sgjava/install-opencv#7]
Hi, I followed the instructions of your repo to install opencv, but i can't found the VideoWriter class in the Java binding, even with the class_ignore_list patch to gen_java.py. did i miss something?

**Comment by sgjava** [comment]
You do not need to patch current 3.0.0-dev and the sed will not do anything if VideoWriter is removed from the ignore list. See https://github.com/Itseez/opencv/pull/5255.
