### ISSUE TITLE
OpenCV 3.0.0 + OpenCL 1.1 slow Odroid-XU4

### ISSUE THREAD

**Issue by urvineet** [sgjava/install-opencv#8]
Hi ,
I Have Odroid-XU4,  i ran script which has  UMat enabled for TAPI but result seems quite slow 
Opencl (false)  HOG + liner SVM
took 1 frame processing 1.2 Sec  
Opencl (true)  HOG + liner SVM
took 1 frame processing 0.9 Sec  

is CPU to GPU moving frame costly or Odroid-xu4 ubuntu not supported OpenCL ??

**Comment by sgjava** [comment]
I haven't built OpenCL from scratch for the Mali yet (just using default one in Ubuntu). If you want to compare notes check out https://github.com/sgjava/install-opencv/blob/master/opencv-python/codeferm/PeopleDetect.py which uses HOG:

cd install-opencv/opencv-python/codeferm
python PeopleDetect.py

You should get about 3-4 FPS (this is with built in OpenCL). My CPU governor settings http://forum.odroid.com/viewtopic.php?f=95&t=18903

HOG is slow period, I only get 6 FPS with a 2.2 GHz quad core desktop. The trick is to use motion detection and ROI like https://github.com/sgjava/peopleroi if possible.
